#!/usr/bin/env sh

SPIN_ENTRY='⠉⠛⠿⣿⠿⠛⠉⠙'
SPIN_LOOP='⠹⢸⣰⣤⣆⡇⠏⠛'

UNIQ_INDEX=$$
OPTION_NAME_SPINNER="@spinner${UNIQ_INDEX}"

setup_tmux_option () {
    option_name="$1"

    option_value="$(tmux show-options -v -g ${option_name})"
    if [ -z "${option_value}" ]; then
        option_value='#{@spinner}'
    fi

    option_value="$(echo ${option_value} | sed 's/#{@spinner}/#{'${OPTION_NAME_SPINNER}'}/g')"
    tmux set-option -w "${option_name}" "${option_value}"
}


teardown_tmux_option () {
    option_name="$1"
    tmux set-option -u -w "${option_name}"
}


setup () {
    setup_tmux_option "window-status-format"
    setup_tmux_option "window-status-current-format"
}


teardown () {
    tmux set-option -g -u "${OPTION_NAME_SPINNER}"
    teardown_tmux_option "window-status-format"
    teardown_tmux_option "window-status-current-format"
    stop_animate
}


animate () {
    i=0
    while [ $i -lt ${#SPIN_ENTRY} ]; do
        tmux set-option -g "${OPTION_NAME_SPINNER}" "${SPIN_ENTRY:$i:1}"
        i=$(( i + 1 ))
        sleep 0.1
    done

    i=0
    while true; do
        tmux set-option -g "${OPTION_NAME_SPINNER}" "${SPIN_LOOP:$i:1}"
        i=$(( (i + 1) % ${#SPIN_LOOP} ))
        sleep 0.1
    done
}


stop_animate () {
    if [ -n "$SPINNER_PID" ]; then
        kill $SPINNER_PID
    fi
}


waitpid () {
    pid="$1"
    if [ -z "$pid" ]; then
        return 1
    fi

    kill -s 0 "$pid" >/dev/null 2>&1
    pid_not_exists="$?"
    if [ $pid_not_exists -ne 0 ]; then
        return "${pid_not_exists}"
    fi

    if command -v caffeinate >/dev/null 2>&1; then
        caffeinate -w "$pid"
        return "$?"

    else
        while kill -s 0 "$pid" >/dev/null 2>&1; do
            sleep 1
        done
    fi
}


usage () {
    proc="$(basename $1)"
    echo 'Usage:'
    echo "$ ${proc}"
    echo "$ ${proc} [-h|--help]"
    echo "$ ${proc} command [args ...]"
    echo "$ ${proc} -w PID"
    exit 1
}


main () {
    trap "teardown; exit" SIGINT SIGTERM

    wait_for_pid=''

    while [ "$#" -ne 0 ]; do
        if [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
            usage "$0"

        elif [ "$1" = '-w' ] || [ "$1" = '--wait' ]; then
            shift
            wait_for_pid="$1"
        else
            break
        fi

        shift
    done

    setup

    animate &
    SPINNER_PID="$!"

    if [ -t 1 ] ; then
        echo 'Spinner PID:' $SPINNER_PID
        echo 'Tmux option:' ${OPTION_NAME_SPINNER}
    fi

    if [ -n "${wait_for_pid}" ]; then
        waitpid "${wait_for_pid}"
        ret="$?"
    elif [ -n "$1" ]; then
        command "$@"
        ret="$?"
    else
        waitpid "${SPINNER_PID}"
        ret="$?"
    fi

    teardown

    return "${ret}"
}


main "$@"
